### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by VitorVRS** [fredrb/spaceExplorer#1]
- [ ] - Layers (parallax/zbuffer)
  - [x] - Parallax
  - [ ] - zbuffer
- [x] - GameObject
- [x] - Text
- [x] - Collision
- [ ] - Elements (asteroids, spaceship, ...)
  - [x] - Enemy spaceship
  - [ ] - Asteroids?
- [x] - Keyboard events
- [x] - Screens (start, game over)
  - [x] - Start
  - [x] - Game Over
- [x] - Score
- [ ] - Custom font (?)

**Comment by VitorVRS** [comment]
@fredrb falta mais alguma coisa aqui?

**Comment by fredrb** [comment]
por enquanto acho que não

**Comment by VitorVRS** [comment]
Apenas pra ficar sabendo, to fazendo a "máquina de estados" que tínhamos mencionado.

**Comment by VitorVRS** [comment]
Adicionado este branch: https://github.com/fredrb/spaceExplorer/tree/feature/multiple-callbacks
Se puder dar uma revisada e ver o que acha.

**Comment by fredrb** [comment]
Coloquei a sprite de inimigo e fiz uma lógica pra gerar eles pseudo randomicamente. Porém a collision não tá funcionando muito bem

**Comment by VitorVRS** [comment]
Adicionei uma classe zbuffer e outro método plot que utilizar o zbuffer.
Fiz várias implementações, todas ficaram ruins (lentas). Acabei não aplicando nenhuma.
Não sei mais como implemenar :disappointed:
